### ISSUE TITLE
[BUG] Garbled non-English DRP text displayed in Discord

### ISSUE THREAD

**Issue by TheWhiteDog9487** [ThePhaseCat/phases-discord-rich-presence#20]
**Describe the bug**
The debug mode output is correct, but Discord displays it incorrectly.
The very weird thing is that I can't reproduce the bug using IDEA, but I can reproduce using the jar I downloaded from Modrinth.

**To Reproduce**
Install the module provided in `gradle.properties` (same version)
Start the game
Enter a single player world

**Expected behavior**
Non-English text is displayed normally, as in the following screenshot of the IDEA launched Minecraft client

**Screenshots**
<img width="1554" alt="Image" src="https://github.com/user-attachments/assets/63d5875f-0d67-4588-b7ba-e7eaf4c22e0b" />
<img width="1297" alt="Image" src="https://github.com/user-attachments/assets/b383dce8-69b9-4f8d-a432-e60abc4096c7" />

**Mods**
The version configured in `gradle.properties`, as well as the version below both reproduce the problem.
Minecraft 1.21.4
Fabric API 0.118.5
phases-discord-rich-presence-2.0.0-1.21-beta1
Fabric Loader 0.16.10
Modmenu 13.0.3

**Log**
If possible, please link your Minecraft Log file using [mclo](https://mclo.gs/)

**Additional context**

**Comment by ThePhaseCat** [comment]
Unable to recreate, my first thought is that it might be a discord and/or library issue, because the variables appear to be being set properly, but getting garbled when sent over to discord?

![Image](https://github.com/user-attachments/assets/fe904338-302c-4737-a364-689a8fc79035)

**Comment by TheWhiteDog9487** [comment]
I'm not sure, as I can't reproduce the problem within IDEA I can't debug to investigate what's wrong, which is very confusing to me.
And I also think it's possible that the new libraries you've recently replaced are causing the problem, as I can see in the game logs that the debug mode output is correct, and I'm now rewinding back to version 1.6.0 with no problems, and the mod from version 1.6.0 are displaying correctly.

**Comment by TheWhiteDog9487** [comment]
I found the cause of the problem.
The HMCL launcher I'm using adds the JVM parameter `-Dfile.encoding=GB18030 -Dstdout.encoding=GB18030 -Dstderr.encoding=GB18030` at startup, it's the one that switches the encoding to GB18030 that causes the garbage, I manually added the parameter to override it to I manually added parameters to override it to UTF-8 and the problem disappeared.

<img width="834" alt="Image" src="https://github.com/user-attachments/assets/7f4ca8ee-01d3-4068-ba3d-5037fbcb50cc" />
<img width="615" alt="Image" src="https://github.com/user-attachments/assets/7dcf1f21-b6c4-4afc-af7d-cccb64c8bd6e" />

[minecraft-exported-jstack-dump-2025-03-28T10-24-59.log](https://github.com/user-attachments/files/19497311/minecraft-exported-jstack-dump-2025-03-28T10-24-59.log)
[minecraft-exported-jstack-dump-2025-03-28T10-29-00.log](https://github.com/user-attachments/files/19497310/minecraft-exported-jstack-dump-2025-03-28T10-29-00.log)

**Comment by ThePhaseCat** [comment]
A bit late for me over here but I will attempt to reproduce this tomorrow with the launcher I use (prism), but this does seem to be something that can't be fixed by my mod?

**Comment by TheWhiteDog9487** [comment]
I'm not sure, I tried to re-encode the details string of the activity to convert to UTF-8, but the problem was not solved.
Considering that previous libraries didn't have this problem, I'm wondering if there could be some problem with `discord-game-sdk4j` support for other character encodings, which causes adding the JVM parameter `-Dfile.encoding` to be garbled?

**Comment by ThePhaseCat** [comment]
Yeah it's probably a library issue, then again I've never run into an issue like this before

**Comment by TheWhiteDog9487** [comment]
https://github.com/JnCrMx/discord-game-sdk4j/issues/99

**Comment by TheWhiteDog9487** [comment]
@ThePhaseCat The issue has been resolved.

**Comment by ThePhaseCat** [comment]
Fixed with v2.5, thanks for waiting!

**Comment by TheWhiteDog9487** [comment]
@ThePhaseCat request to reopen this issue
The same issue reappeared in version 2.8.0 using the same reproduction steps.

**Comment by ThePhaseCat** [comment]
I believe this might be due to the fact I bumped down the library version (and therefore rolled back this bug lol). I can get it fixed by Friday, might take me a little bit since I'm very busy tomororw.
